name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: install
      working-directory: ./T1
      run: make install
    - name: compile files
      working-directory: ./T1
      run: make compile
    - name: T1
      id: t1a
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t1a
        setup-command: ''
        command: "./T1/compl"
        comparison-method: exact
        timeout: 10
        max-score: 10
        input: |-
a
b
_c
d_
7
_
fifa
FIFA
linguagem
Linguagem
_linguagem
linguagem_
linguag3m
1inguagem
lingua-gem
        expected-output: |-
(1,ID,"a")
(2,ID,"b")
(3,ERROR,"_")
(3,ID,"c")
(4,ID,"d_")
(5,NUM,"7")
(6,ERROR,"_")
(7,ID,"fifa")
(8,ID,"FIFA")
(9,ID,"linguagem")
(10,ID,"Linguagem")
(11,ERROR,"_")
(11,ID,"linguagem")
(12,ID,"linguagem_")
(13,ID,"linguag3m")
(14,NUM,"1")
(14,ID,"inguagem")
(15,ID,"lingua")
(15,SYM,"-")
(15,ID,"gem")
    - name: T1
      id: t1b
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t1b
        setup-command: ''
        command: "./T1/compl"
        comparison-method: exact
        timeout: 10
        max-score: 10
        input: |-
boolean
else
false
function
if
integer
print
return
string
true
void
while
for
char
        expected-output: |-
(1,KEYW,"boolean")
(2,KEYW,"else")
(3,KEYW,"false")
(4,KEYW,"function")
(5,KEYW,"if")
(6,KEYW,"integer")
(7,KEYW,"print")
(8,KEYW,"return")
(9,ID,"string")
(10,KEYW,"true")
(11,KEYW,"void")
(12,KEYW,"while")
(13,ID,"for")
(14,ID,"char")
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1A_RESULTS: "${{steps.t1a.outputs.result}}"
        T1B_RESULTS: "${{steps.t1b.outputs.result}}"
      with:
        runners: t1a, t1b
